
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Oct  8 2025 15:16:36 IST (Oct  8 2025 09:46:36 UTC)

// Verification Directory fv/top 


'timescale 1ns / 10ps
module top(clk_main, clk_ped, rst_main_n, rst_ped_n, button,
     traffic_light, walk);
  input clk_main, clk_ped, rst_main_n, rst_ped_n, button;
  output [1:0] traffic_light;
  output walk;
  wire clk_main, clk_ped, rst_main_n, rst_ped_n, button;
  wire [1:0] traffic_light;
  wire walk;
  wire U_PED_btn_ff, U_sync_ack_to_main_sync1,
       U_sync_grant_to_ped_sync1, U_sync_req_to_main_sync1,
       ack_toggle_main_sync, ack_toggle_ped, grant_toggle_main,
       grant_toggle_ped_sync;
  wire granted, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, pending_request, prev_ack_main,
       prev_req_main, req_toggle_main_sync;
  wire req_toggle_ped;
  decrq1 pending_request_reg(.CDN (rst_main_n), .CP (clk_main), .D
       (n_14), .ENN (n_18), .Q (pending_request));
  decrq1 granted_reg(.CDN (rst_main_n), .CP (clk_main), .D (n_16), .ENN
       (n_17), .Q (granted));
  aoi211d1 g193__2398(.A (n_15), .B (n_11), .C1 (req_toggle_main_sync),
       .C2 (prev_req_main), .ZN (n_18));
  dfcrq1 U_PED_ack_toggle_out_reg(.CDN (rst_ped_n), .CP (clk_ped), .D
       (n_13), .Q (ack_toggle_ped));
  nr02d0 g191__5107(.A1 (n_16), .A2 (n_15), .ZN (n_17));
  inv0d0 g196(.I (n_15), .ZN (n_14));
  dfcrq1 U_PED_walk_reg(.CDN (rst_ped_n), .CP (clk_ped), .D (n_10), .Q
       (walk));
  oaim22d1 g192__6260(.A1 (n_12), .A2 (ack_toggle_ped), .B1 (n_12), .B2
       (ack_toggle_ped), .ZN (n_13));
  aoim22d1 g198__4319(.A1 (ack_toggle_main_sync), .A2 (prev_ack_main),
       .B1 (ack_toggle_main_sync), .B2 (prev_ack_main), .Z (n_15));
  dfcrq1 grant_toggle_main_reg(.CDN (rst_main_n), .CP (clk_main), .D
       (n_9), .Q (grant_toggle_main));
  nr02d1 g199__8428(.A1 (prev_req_main), .A2 (req_toggle_main_sync),
       .ZN (n_11));
  dfcrq1 U_PED_req_toggle_out_reg(.CDN (rst_ped_n), .CP (clk_ped), .D
       (n_7), .Q (req_toggle_ped));
  inv0d0 g201(.I (n_12), .ZN (n_10));
  dfcrn1 prev_ack_main_reg(.CDN (rst_main_n), .CP (clk_main), .D (n_4),
       .QN (prev_ack_main));
  aoim22d1 g203__5526(.A1 (ack_toggle_ped), .A2
       (grant_toggle_ped_sync), .B1 (ack_toggle_ped), .B2
       (grant_toggle_ped_sync), .Z (n_12));
  oaim22d1 g200__6783(.A1 (n_8), .A2 (grant_toggle_main), .B1 (n_8),
       .B2 (grant_toggle_main), .ZN (n_9));
  oaim22d1 g202__3680(.A1 (req_toggle_ped), .A2 (n_6), .B1
       (req_toggle_ped), .B2 (n_6), .ZN (n_7));
  dfcrq1 prev_req_main_reg(.CDN (rst_main_n), .CP (clk_main), .D (n_5),
       .Q (prev_req_main));
  dfcrq1 \U_TRAFFIC_traffic_light_reg[1] (.CDN (rst_main_n), .CP
       (clk_main), .D (n_3), .Q (traffic_light[1]));
  inv0d0 g213(.I (n_8), .ZN (n_16));
  dfcrn1 U_sync_grant_to_ped_sync_out_reg(.CDN (rst_ped_n), .CP
       (clk_ped), .D (U_sync_grant_to_ped_sync1), .QN
       (grant_toggle_ped_sync));
  oai21d1 g215__1617(.A (n_2), .B1 (traffic_light[1]), .B2 (n_1), .ZN
       (n_3));
  nd02d1 g216__2802(.A1 (button), .A2 (U_PED_btn_ff), .ZN (n_6));
  nd04d1 g217__1705(.A1 (n_2), .A2 (traffic_light[1]), .A3 (n_1), .A4
       (pending_request), .ZN (n_8));
  nr03d1 g214__5122(.A1 (granted), .A2 (traffic_light[0]), .A3
       (traffic_light[1]), .ZN (n_0));
  dfcrq1 U_sync_req_to_main_sync1_reg(.CDN (rst_main_n), .CP
       (clk_main), .D (req_toggle_ped), .Q (U_sync_req_to_main_sync1));
  dfcrn1 U_PED_btn_ff_reg(.CDN (rst_ped_n), .CP (clk_ped), .D (button),
       .QN (U_PED_btn_ff));
  dfcrq1 U_sync_ack_to_main_sync1_reg(.CDN (rst_main_n), .CP
       (clk_main), .D (ack_toggle_ped), .Q (U_sync_ack_to_main_sync1));
  dfcrq1 U_sync_grant_to_ped_sync1_reg(.CDN (rst_ped_n), .CP (clk_ped),
       .D (grant_toggle_main), .Q (U_sync_grant_to_ped_sync1));
  inv0d0 g223(.I (granted), .ZN (n_2));
  dfcrb1 U_sync_req_to_main_sync_out_reg(.CDN (rst_main_n), .CP
       (clk_main), .D (U_sync_req_to_main_sync1), .Q (n_5), .QN
       (req_toggle_main_sync));
  dfcrb1 U_sync_ack_to_main_sync_out_reg(.CDN (rst_main_n), .CP
       (clk_main), .D (U_sync_ack_to_main_sync1), .Q (n_4), .QN
       (ack_toggle_main_sync));
  dfcrb1 \U_TRAFFIC_traffic_light_reg[0] (.CDN (rst_main_n), .CP
       (clk_main), .D (n_0), .Q (traffic_light[0]), .QN (n_1));
endmodule

